curriculum/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import *


app_name = "curriculum"

urlpatterns = [
    
    path('classic/',export_classic,name='classic'),
    path('classic1/',export_classic1,name='classic1'),
    path('modern/',export_single_page,name='modern'),
    #path('htmltest/<str:first_name>/',export_class,name='test'),
    path('viewCV/',export_class,name='viewCV'),
    path('profileview/',profileView,name='profileview'),
    path('htmltest/',export_classic2,name='test'),

    
    path('languageitem/',addlanguageitem,name='languageitem'),
    path('resume/',addresume,name='resume'),
    # path('skill/',addskill,name='skill'),
    path('skillitem/',addskillitem,name='skillitem'),
    # path('certification/',addcertification,name='certification'),
    path('certificationitem/',addcertificationitem,name='certificationitem'),
    path('experience/',addexperience,name='experience'),
    # path('project/',addproject,name='project'),
    path('projectitem/',addprojectitem,name='projectitem'),
    path('training/',addtraining,name='training'),
    path('cv/',resume_generate,name='resume_generate'),
    path('edit_profile/',menulist,name='showmenu'),
    path('updateresume/',EditProfileView.as_view(),name='updateResume'),
    

    path('updatetraining/',TrainingListView.as_view(),name='updatetraining'),
    path('updatetraining/<int:id>', UpdateTrainingView.as_view(), name='update_training'),
    path('deletetraining/<int:id>', TrainingDeleteView.as_view(), name='delete_training'),

    path('updateskill',SkillListView.as_view(),name='updateskill'),
    path('updateskill/<int:id>', UpdateSkillView.as_view(), name='update_skill'),
    path('deleteskill/<int:id>', SkillDeleteView.as_view(), name='delete_skill'),


    path('updateproject',ProjectListView.as_view(),name='updateproject'),
    path('updateproject/<int:id>', UpdateProjectView.as_view(), name='update_project'),
    path('deleteproject/<int:id>', ProjectDeleteView.as_view(), name='delete_project'),





    path('updatelanguage',LanguageListView.as_view(),name='updatelanguage'),
    path('updatelanguage/<int:id>', UpdateLanguageView.as_view(), name='update_language'),
    path('deletelanguage/<int:id>', LanguageDeleteView.as_view(), name='delete_language'),


    path('updateexperience',ExperienceListView.as_view(),name='updateexperience'),
    path('updateexperience/<int:id>', UpdateExperienceView.as_view(), name='update_experience'),
    path('deleteexperience/<int:id>', ExperienceDeleteView.as_view(), name='delete_experience'),


    path('updatecertification',CertificationListView.as_view(),name='updatecertification'),
    path('updatecertification/<int:id>', UpdateCertificationView.as_view(), name='update_certification'),
    path('deletecertification/<int:id>', CertificationDeleteView.as_view(), name='delete_certification'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import activate
from django.contrib.auth import views as auth_views
from curriculum.views import export_single_page, export_classic, export_class,export_classic1,addlanguageitem,addresume, addskillitem, addcertificationitem, addexperience, addprojectitem, addtraining, menulist
from jobsapp.views import search_box

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/search/', search_box, name='search_box'),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),





    path('employee/', include('curriculum.urls')),





    path('activate/<uidb64>/<token>',
        activate, name='activate'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password/password_reset.html'
         ),
         name='password-reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password/password_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curriculum/models/certification.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from curriculum.models.utils import YEARS, MONTHS

from django.conf import settings



@python_2_unicode_compatible
class CertificationItem(models.Model):
    title = models.CharField(max_length=50, verbose_name=_("title"),default=None)
    authority = models.CharField(max_length=200, verbose_name=_("authority"),default=None,help_text=_("eg. Google"))
    url = models.URLField(max_length=300, blank=True, verbose_name=_("URL"),default=None)

    resume = models.ForeignKey("curriculum.Resume", related_name='certifications',on_delete=models.CASCADE,default=None)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='certifications',on_delete=models.CASCADE,default=None)

    end_year = models.IntegerField(choices=YEARS, verbose_name=_("Certified year"))
    end_month = models.IntegerField(choices=MONTHS, null=True, blank=True, verbose_name=_("Certified month"))

    class Meta:
        app_label = 'curriculum'
        

    def __str__(self):
        return _('%(title)s at %(authority)s') % \
                {'title': self.title, 'authority': self.authority}

curriculum/models/language.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from django.conf import settings
LANGUAGE_LEVELS = (
    ('NOT', _("Notion")),
    ('BAS', _('basic')),
    ('ADV', _('advanced')),
    ('PRO', _('professional')),
    ('BIL', _('bilingual')),
)



@python_2_unicode_compatible
class LanguageItem(models.Model):
    resume = models.ForeignKey("curriculum.Resume", related_name='languages',on_delete=models.CASCADE,default=None)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='languages',on_delete=models.CASCADE,default=None)
    language = models.CharField(max_length=50, verbose_name=_("name"))
    level = models.CharField(max_length=5, choices=LANGUAGE_LEVELS,null=True, blank=True, default=LANGUAGE_LEVELS[0][0], verbose_name=_('level'))
    
    class Meta:
        app_label = 'curriculum'
        unique_together = ('language', 'user')

    def __str__(self):
        return self.language

curriculum/revealjs/models.py
from django.db import models

# Create your models here.

curriculum/revealjs/views.py
from django.shortcuts import render, get_object_or_404
from curriculum.models import Resume


def get_resume(request, resume_id):
    resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    return render(request, 'revealjs.html', {
        'resume': resume,
        'skills': resume.skills.order_by('category', '-weight'),
        'projects': resume.projects.order_by('-weight'),
        'experiences': resume.experiences.order_by('-start_year'),
        'trainings': resume.trainings.order_by('-year', '-month'),
        'certifications': resume.certifications.order_by('-start_year', '-start_month')
    })

curriculum/views.py
"""
Views that can used by developer for easily export resume as PDF.
"""
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from curriculum import export
from curriculum import models
from curriculum.models import Resume,ProjectItem,SkillItem,CertificationItem,Training,Experience, LanguageItem
from accounts.models import User
from django.template.loader import get_template
from curriculum.forms import LanguageItemForm, ResumeForm, SkillItemForm, CertificationItemForm, ExperienceForm, ProjectItemForm, TrainingForm, LanguageFormset, SkillFormset, UpdateResumeForm, UpdateTrainingForm,UpdateSkillitemForm, UpdateProjectitemForm, UpdateExperienceForm,UpdateLanguageitemForm, UpdateCertificationitemForm

from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from jobsapp.decorators import user_can_search,user_is_employer,user_is_superuser,user_is_employee
from django.core.exceptions import PermissionDenied


@login_required(login_url=reverse_lazy('accounts:login'))
def export_single_page(request):
    """Get a resume in a single page PDF."""
    #resume = get_object_or_404(Resume.objects.filter(firstname='Vijay'))
    current_user=request.user
    try:
        pdf, result = export.export_pdf(current_user, export.single_page)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_classic(request):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(user=request.user))
    current_user=request.user

    try:
        pdf, result = export.export_pdf(current_user, export.classic)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_classic2(request):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(user=request.user))
    current_user=request.user
    try:
        pdf, result = export.export_pdf(current_user, export.classic2)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_classic1(request):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(firstname='Vijay'))
    current_user=request.user
    try:
        pdf, result = export.export_pdf(current_user, export.classic1)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_class(request):
    """
    Create a classic resume in :mod:`xhtml2pdf` format.
    """
    try:
        resume = get_object_or_404(Resume.objects.filter(user=request.user))
        current_user = request.user
        context = {
            'pagesize': 'a4',
            'resume': resume,
            'skills': current_user.skills.order_by('category'),
            'projects': current_user.projects.order_by('-weight'),
            'experiences': current_user.experiences.order_by('-start_year'),
            'trainings': current_user.trainings.order_by('-start_year', '-start_month'),
            'certifications': current_user.certifications.order_by('-end_year', '-end_month'),
        }
        return render(request,'curriculum/cvpreview.html',context)
    except:
        return render(request,'Errors/profile_error.html')




@login_required(login_url=reverse_lazy('accounts:login'))
def profileView(request):
    """
    Create a classic resume in :mod:`xhtml2pdf` format.
    """
    try:
        resume = get_object_or_404(Resume.objects.filter(user=request.user))
        current_user = request.user
        context = {
            'pagesize': 'a4',
            'resume': resume,
            'skills': current_user.skills.order_by('category'),
            'projects': current_user.projects.order_by('-weight'),
            'experiences': current_user.experiences.order_by('-start_year'),
            'trainings': current_user.trainings.order_by('-start_year', '-start_month'),
            'certifications': current_user.certifications.order_by('-end_year', '-end_month'),
            'language':current_user.languages.order_by('level'),
        }
        return render(request,'curriculum/profileview.html',context)
    except:
        return render(request,'Errors/profile_error.html')

"""
def skillitem(request):
    if request.method=="POST":
        form=ExperienceForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect()
            except:
                pass
    else:
        form=ExperienceForm()
    return render(request,"producttemp.html",{'form':form})
"""


# @login_required(login_url=reverse_lazy('accounts:login'))
# def addlanguageitem(request):
#     if request.method == 'POST':
#         language = request.POST.getlist('language')
#         print(language)
#     form=LanguageItemForm(request.POST or None)
#     try:
#         if form.is_valid():
#             instance=form.save(commit=False)
#             instance.user=request.user
#             instance.resume= Resume.objects.get(user=request.user)
#             instance.save()
#             messages.success(request, f'Your account has been updated!')
#             return redirect('curriculum:languageitem')

#         context={
#             'form':form,
#             'languageitem_active':"active"
#         }
#         return render(request,"curriculum/languageitem.html",context)
#     except ObjectDoesNotExist:
#         messages.success(request, f'Please create resume before you add in details')
#         return redirect('curriculum:resume')


@login_required(login_url=reverse_lazy('accounts:login'))
def addlanguageitem(request):
    template_name = 'curriculum/languageitem.html'
    # heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset = LanguageFormset(queryset=models.LanguageItem.objects.filter(user=request.user))
    if request.method == 'POST':
        formset = LanguageFormset(request.POST)
        try:

            if formset.is_valid():
                for form in formset:
                # only save if name is present
                    if form.cleaned_data.get('language'):
                        instance=form.save(commit=False)
                        instance.user=request.user
                        instance.resume= Resume.objects.get(user=request.user)
                        instance.save()
                return redirect('curriculum:languageitem')
        except IntegrityError:
            messages.success(request, f'You have already added that language!!!')
            return redirect('curriculum:languageitem')
        except ObjectDoesNotExist:
            messages.success(request, f'Please create resume before you add in details')
            return redirect('curriculum:resume')

    return render(request, template_name, {
        'formset': formset,
        'languageitem_active':"active",
    })

@login_required(login_url=reverse_lazy('accounts:login'))
def addresume(request):
    form=ResumeForm(request.POST or None, request.FILES)
    obj=User.objects.filter(email=request.user)
    # instance.user=request.user
    try:
        if form.is_valid():
            instance=form.save(commit=False)
            instance.user=request.user
            # print(instance.user)
            instance.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('curriculum:training')

        context={
            'form':form,
            'obj':obj,
            'resume_active':"active"
        }
        return render(request,"curriculum/resume.html",context)
    except IntegrityError:
        #return HttpResponse("ERROR!!! You have already filled your basic information. Go to update CV in update profile to change information")
        messages.success(request, f'You are trying to  create new instance of your resume when you already have one. You cannot do that, please make changes to your resume here')
        return redirect('curriculum:updateResume')






# @login_required(login_url=reverse_lazy('accounts:login'))
# def addskillitem(request):
#     form=SkillItemForm(request.POST or None, request.FILES)
#     try:
#         if form.is_valid():
#             instance=form.save(commit=False)
#             instance.user=request.user
#             instance.resume= Resume.objects.get(user=request.user)
#             instance.save()

curriculum/templates/curriculum/update/certificationitem.html
{% extends 'update_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
<div class="col-lg-7 offset-3 mx-auto">
    <div class="box rounded">
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            <div class="form-row">

            <div class="form-group col-md-6 mb-0">
                {% for field in form %}
                {% if field.name == 'title' %}
                            <label for="id_{{ field.name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value|default_if_none:'' }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                {% endif %}
                {% endfor %}
            </div>
            <div class="form-group col-md-6 mb-0">
                {% for field in form %}
                {% if field.name == 'authority' %}
                            <label for="id_{{ field.name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value|default_if_none:'' }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <br>

                {% for field in form %}
                {% if field.name == 'url' %}
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value|default_if_none:'' }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                {% endif %}
                {% endfor %}
            <br>


        <div class="form-row">

            <div class="form-group col-md-6 mb-0">
                {% for field in form %}
                {% if field.name == 'end_year' %}
                            <label for="id_{{ field.name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value|default_if_none:'' }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                {% endif %}
                {% endfor %}
            </div>
            <div class="form-group col-md-6 mb-0">
                {% for field in form %}
                {% if field.name == 'end_month' %}
                            <label for="id_{{ field.name }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}"
                                   class="form-control"
                                   name="{{ field.name }}"
                                   id="id_{{ field.name }}"
                                   value="{{ field.value|default_if_none:'' }}"
                                   placeholder="{{ field.field.widget.attrs.placeholder }}">
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <br>

                <div class="text-center">
                    <button type="submit" class="btn btn-info btn-lg btn-block">
                         Update
                    </button>
                </div>

        </form> </br>
        <form action="{% url 'curriculum:delete_certification' view.kwargs.id %}" method="POST">
	        {% csrf_token %}
	            <div class="text-center">
                    <button type="submit" class="btn btn-info btn-lg btn-block">
                         Delete
                    </button>
                </div>

        </form>
    </div>
</div>


    {% endblock %}

curriculum/templates/curriculum/update/certificationlist.html
{% extends 'update_base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}



        <div class="col-lg-5 offset-3 mx-auto">
            <section>
            <h3 class="heading">select the item you want to update</h3>
            {% for certification in certifications %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">

                                    <h4>{{ certification.title }} </h4>
                                </div>
                            </div>
                        </div>



                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:update_certification' certification.id %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            {% endfor %}


            </section>
            <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:certificationitem'   %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i> Add new items
                                        </a>
                                </div>

                            </div>
                        </div>

        </div>



    {% endblock %}

curriculum/templates/curriculum/update/experiencelist.html
{% extends 'update_base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}



        <div class="col-lg-5 offset-3 mx-auto">
            <section>
            <h3 class="heading">select the item you want to update</h3>
            {% for experience in experiences %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">

                                    <h4>{{ experience.title }} at {{experience.entreprise}} </h4>
                                </div>
                            </div>
                        </div>
                         <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:update_experience' experience.id  %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            {% endfor %}
            </section>

            <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:experience'   %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i> Add new items
                                        </a>
                                </div>

                            </div>
                        </div>

        </div>



    {% endblock %}

curriculum/templates/curriculum/update/projectlist.html
{% extends 'update_base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}



        <div class="col-lg-5 offset-3 mx-auto">
            <section>
            <h3 class="heading">select the item you want to update</h3>
            {% for project in projects %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">

                                     <h4>{{ project.title  }} </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{% url 'curriculum:update_project' project.id %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            {% endfor %}
            </section>

            <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:projectitem'   %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i> Add new items
                                        </a>
                                </div>

                            </div>
                        </div>
        </div>



    {% endblock %}

curriculum/templates/curriculum/update/skilllist.html
{% extends 'update_base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}



        <div class="col-lg-5 offset-3 mx-auto">
            <section>
            <h3 class="heading">select the item you want to update</h3>
            {% for skill in skills %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <h4>{{ skill.skill }} </h4>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:update_skill' skill.id %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            {% endfor %}

            </section>

            <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:skillitem'   %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i> Add new items
                                        </a>
                                </div>

                            </div>
                        </div>

        </div>



    {% endblock %}