curriculum/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import *


app_name = "curriculum"

urlpatterns = [
    
    path('classic/',export_classic,name='classic'),
    path('classic1/',export_classic1,name='classic1'),
    path('modern/',export_single_page,name='modern'),
    #path('htmltest/<str:first_name>/',export_class,name='test'),
    path('viewCV/',export_class,name='viewCV'),
    path('profileview/',profileView,name='profileview'),
    path('htmltest/',export_classic2,name='test'),

    
    path('languageitem/',addlanguageitem,name='languageitem'),
    path('resume/',addresume,name='resume'),
    # path('skill/',addskill,name='skill'),
    path('skillitem/',addskillitem,name='skillitem'),
    # path('certification/',addcertification,name='certification'),
    path('certificationitem/',addcertificationitem,name='certificationitem'),
    path('experience/',addexperience,name='experience'),
    # path('project/',addproject,name='project'),
    path('projectitem/',addprojectitem,name='projectitem'),
    path('training/',addtraining,name='training'),
    path('cv/',resume_generate,name='resume_generate'),
    path('edit_profile/',menulist,name='showmenu'),
    path('updateresume/',EditProfileView.as_view(),name='updateResume'),
    

    path('updatetraining/',TrainingListView.as_view(),name='updatetraining'),
    path('updatetraining/<int:id>', UpdateTrainingView.as_view(), name='update_training'),
    path('deletetraining/<int:id>', TrainingDeleteView.as_view(), name='delete_training'),

    path('updateskill',SkillListView.as_view(),name='updateskill'),
    path('updateskill/<int:id>', UpdateSkillView.as_view(), name='update_skill'),
    path('deleteskill/<int:id>', SkillDeleteView.as_view(), name='delete_skill'),


    path('updateproject',ProjectListView.as_view(),name='updateproject'),
    path('updateproject/<int:id>', UpdateProjectView.as_view(), name='update_project'),
    path('deleteproject/<int:id>', ProjectDeleteView.as_view(), name='delete_project'),





    path('updatelanguage',LanguageListView.as_view(),name='updatelanguage'),
    path('updatelanguage/<int:id>', UpdateLanguageView.as_view(), name='update_language'),
    path('deletelanguage/<int:id>', LanguageDeleteView.as_view(), name='delete_language'),


    path('updateexperience',ExperienceListView.as_view(),name='updateexperience'),
    path('updateexperience/<int:id>', UpdateExperienceView.as_view(), name='update_experience'),
    path('deleteexperience/<int:id>', ExperienceDeleteView.as_view(), name='delete_experience'),


    path('updatecertification',CertificationListView.as_view(),name='updatecertification'),
    path('updatecertification/<int:id>', UpdateCertificationView.as_view(), name='update_certification'),
    path('deletecertification/<int:id>', CertificationDeleteView.as_view(), name='delete_certification'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import activate
from django.contrib.auth import views as auth_views
from curriculum.views import export_single_page, export_classic, export_class,export_classic1,addlanguageitem,addresume, addskillitem, addcertificationitem, addexperience, addprojectitem, addtraining, menulist
from jobsapp.views import search_box

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/search/', search_box, name='search_box'),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),





    path('employee/', include('curriculum.urls')),





    path('activate/<uidb64>/<token>',
        activate, name='activate'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password/password_reset.html'
         ),
         name='password-reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password/password_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curriculum/models/certification.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from curriculum.models.utils import YEARS, MONTHS

from django.conf import settings



@python_2_unicode_compatible
class CertificationItem(models.Model):
    title = models.CharField(max_length=50, verbose_name=_("title"),default=None)
    authority = models.CharField(max_length=200, verbose_name=_("authority"),default=None,help_text=_("eg. Google"))
    url = models.URLField(max_length=300, blank=True, verbose_name=_("URL"),default=None)

    resume = models.ForeignKey("curriculum.Resume", related_name='certifications',on_delete=models.CASCADE,default=None)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='certifications',on_delete=models.CASCADE,default=None)

    end_year = models.IntegerField(choices=YEARS, verbose_name=_("Certified year"))
    end_month = models.IntegerField(choices=MONTHS, null=True, blank=True, verbose_name=_("Certified month"))

    class Meta:
        app_label = 'curriculum'
        

    def __str__(self):
        return _('%(title)s at %(authority)s') % \
                {'title': self.title, 'authority': self.authority}

curriculum/models/language.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from django.conf import settings
LANGUAGE_LEVELS = (
    ('NOT', _("Notion")),
    ('BAS', _('basic')),
    ('ADV', _('advanced')),
    ('PRO', _('professional')),
    ('BIL', _('bilingual')),
)



@python_2_unicode_compatible
class LanguageItem(models.Model):
    resume = models.ForeignKey("curriculum.Resume", related_name='languages',on_delete=models.CASCADE,default=None)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='languages',on_delete=models.CASCADE,default=None)
    language = models.CharField(max_length=50, verbose_name=_("name"))
    level = models.CharField(max_length=5, choices=LANGUAGE_LEVELS,null=True, blank=True, default=LANGUAGE_LEVELS[0][0], verbose_name=_('level'))
    
    class Meta:
        app_label = 'curriculum'
        unique_together = ('language', 'user')

    def __str__(self):
        return self.language

curriculum/revealjs/models.py
from django.db import models

# Create your models here.

curriculum/revealjs/views.py
from django.shortcuts import render, get_object_or_404
from curriculum.models import Resume


def get_resume(request, resume_id):
    resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    return render(request, 'revealjs.html', {
        'resume': resume,
        'skills': resume.skills.order_by('category', '-weight'),
        'projects': resume.projects.order_by('-weight'),
        'experiences': resume.experiences.order_by('-start_year'),
        'trainings': resume.trainings.order_by('-year', '-month'),
        'certifications': resume.certifications.order_by('-start_year', '-start_month')
    })

curriculum/views.py
"""
Views that can used by developer for easily export resume as PDF.
"""
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from curriculum import export
from curriculum import models
from curriculum.models import Resume,ProjectItem,SkillItem,CertificationItem,Training,Experience, LanguageItem
from accounts.models import User
from django.template.loader import get_template
from curriculum.forms import LanguageItemForm, ResumeForm, SkillItemForm, CertificationItemForm, ExperienceForm, ProjectItemForm, TrainingForm, LanguageFormset, SkillFormset, UpdateResumeForm, UpdateTrainingForm,UpdateSkillitemForm, UpdateProjectitemForm, UpdateExperienceForm,UpdateLanguageitemForm, UpdateCertificationitemForm

from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from jobsapp.decorators import user_can_search,user_is_employer,user_is_superuser,user_is_employee
from django.core.exceptions import PermissionDenied


@login_required(login_url=reverse_lazy('accounts:login'))
def export_single_page(request):
    """Get a resume in a single page PDF."""
    #resume = get_object_or_404(Resume.objects.filter(firstname='Vijay'))
    current_user=request.user
    try:
        pdf, result = export.export_pdf(current_user, export.single_page)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_classic(request):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(user=request.user))
    current_user=request.user

    try:
        pdf, result = export.export_pdf(current_user, export.classic)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_classic2(request):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(user=request.user))
    current_user=request.user
    try:
        pdf, result = export.export_pdf(current_user, export.classic2)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_classic1(request):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(firstname='Vijay'))
    current_user=request.user
    try:
        pdf, result = export.export_pdf(current_user, export.classic1)
        raw_pdf = result.getvalue()
        if not pdf.err:
            return HttpResponse(raw_pdf, content_type='application/pdf')
        return HttpResponse('We had some errors.')
    except:
        return render(request,'Errors/CV_error.html')

@login_required(login_url=reverse_lazy('accounts:login'))
def export_class(request):
    """
    Create a classic resume in :mod:`xhtml2pdf` format.
    """
    try:
        resume = get_object_or_404(Resume.objects.filter(user=request.user))
        current_user = request.user
        context = {
            'pagesize': 'a4',
            'resume': resume,
            'skills': current_user.skills.order_by('category'),
            'projects': current_user.projects.order_by('-weight'),
            'experiences': current_user.experiences.order_by('-start_year'),
            'trainings': current_user.trainings.order_by('-start_year', '-start_month'),
            'certifications': current_user.certifications.order_by('-end_year', '-end_month'),
        }
        return render(request,'curriculum/cvpreview.html',context)
    except:
        return render(request,'Errors/profile_error.html')




@login_required(login_url=reverse_lazy('accounts:login'))
def profileView(request):
    """
    Create a classic resume in :mod:`xhtml2pdf` format.
    """
    try:
        resume = get_object_or_404(Resume.objects.filter(user=request.user))
        current_user = request.user
        context = {
            'pagesize': 'a4',
            'resume': resume,
            'skills': current_user.skills.order_by('category'),
            'projects': current_user.projects.order_by('-weight'),
            'experiences': current_user.experiences.order_by('-start_year'),
            'trainings': current_user.trainings.order_by('-start_year', '-start_month'),
            'certifications': current_user.certifications.order_by('-end_year', '-end_month'),
            'language':current_user.languages.order_by('level'),
        }
        return render(request,'curriculum/profileview.html',context)
    except:
        return render(request,'Errors/profile_error.html')

"""
def skillitem(request):
    if request.method=="POST":
        form=ExperienceForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect()
            except:
                pass
    else:
        form=ExperienceForm()
    return render(request,"producttemp.html",{'form':form})
"""


# @login_required(login_url=reverse_lazy('accounts:login'))
# def addlanguageitem(request):
#     if request.method == 'POST':
#         language = request.POST.getlist('language')
#         print(language)
#     form=LanguageItemForm(request.POST or None)
#     try:
#         if form.is_valid():
#             instance=form.save(commit=False)
#             instance.user=request.user
#             instance.resume= Resume.objects.get(user=request.user)
#             instance.save()
#             messages.success(request, f'Your account has been updated!')
#             return redirect('curriculum:languageitem')

#         context={
#             'form':form,
#             'languageitem_active':"active"
#         }
#         return render(request,"curriculum/languageitem.html",context)
#     except ObjectDoesNotExist:
#         messages.success(request, f'Please create resume before you add in details')
#         return redirect('curriculum:resume')


@login_required(login_url=reverse_lazy('accounts:login'))
def addlanguageitem(request):
    template_name = 'curriculum/languageitem.html'
    # heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset = LanguageFormset(queryset=models.LanguageItem.objects.filter(user=request.user))
    if request.method == 'POST':
        formset = LanguageFormset(request.POST)
        try:

            if formset.is_valid():
                for form in formset:
                # only save if name is present
                    if form.cleaned_data.get('language'):
                        instance=form.save(commit=False)
                        instance.user=request.user
                        instance.resume= Resume.objects.get(user=request.user)
                        instance.save()
                return redirect('curriculum:languageitem')
        except IntegrityError:
            messages.success(request, f'You have already added that language!!!')
            return redirect('curriculum:languageitem')
        except ObjectDoesNotExist:
            messages.success(request, f'Please create resume before you add in details')
            return redirect('curriculum:resume')

    return render(request, template_name, {
        'formset': formset,
        'languageitem_active':"active",
    })

@login_required(login_url=reverse_lazy('accounts:login'))
def addresume(request):
    form=ResumeForm(request.POST or None, request.FILES)
    obj=User.objects.filter(email=request.user)
    # instance.user=request.user
    try:
        if form.is_valid():
            instance=form.save(commit=False)
            instance.user=request.user
            # print(instance.user)
            instance.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('curriculum:training')

        context={
            'form':form,
            'obj':obj,
            'resume_active':"active"
        }
        return render(request,"curriculum/resume.html",context)
    except IntegrityError:
        #return HttpResponse("ERROR!!! You have already filled your basic information. Go to update CV in update profile to change information")
        messages.success(request, f'You are trying to  create new instance of your resume when you already have one. You cannot do that, please make changes to your resume here')
        return redirect('curriculum:updateResume')






# @login_required(login_url=reverse_lazy('accounts:login'))
# def addskillitem(request):
#     form=SkillItemForm(request.POST or None, request.FILES)
#     try:
#         if form.is_valid():
#             instance=form.save(commit=False)
#             instance.user=request.user
#             instance.resume= Resume.objects.get(user=request.user)
#             instance.save()

curriculum/templates/curriculum/classic.html
{% load i18n curriculum %}

<html>
 <head>
  <style type="text/css">
  @page {
    size: {{ pagesize }};
    margin: 1cm;
    border: 0pt solid white;
  }
  * {
    font-size: 14px;
    line-height: 15px;
  }
  .center {
    text-align: center;
  }
  a[href], .h1, .h2 {
    color: #0066B2;
  }
  .h1 {
    font-size: 50px;
  }
  .h2 {
    font-size: 20px;
  }
  .h3 {
    font-size: 16px;
    color: #3066B2;
  }
  .h3 small {
    color: rgba(10, 3, 3, 0.856);
  }
  .separator {
    border: 3px;
    line-height: 0px;
  }
  </style>
 </head>
 <body>
    <div id="content_frame">
      <table>
        <tr>
          <td style="width: 330px">
            {% if resume.image %}
            <img height="120" width="120" src="{{ resume.image.url }}"/>
            {% endif %}
          </td>
          <td class="center">
            <h1 class="h1">{{ resume.firstname }} {{ resume.middlename|default_if_none:'' }} {{ resume.lastname }}<br>{% if resume.title %}<br>{{ resume.title }}{% endif %}</h1>
            {% if resume.resume %}<i>{{ resume.resume }}</i>{% endif %}
          </td>
          <td style="width: 330px; text-align: right">
              {% if resume.phone %}{{ resume.phone }}<br>{% endif %}
              {% if resume.city or resume.country %}{{ resume.city|default:"" }} {{ resume.country|default:"" }}<br>{% endif %}
              {% if resume.address %}{{ resume.address }}<br>{% endif %}
              {% if resume.email %}<a href="mailto:{{ resume.email }}">{{ resume.email }}</a><br>{% endif %}
              {% if resume.website %}{{ resume.website|shortlink|safe }}<br>{% endif %}
              {% if resume.skype %}<b>LinkedIn</b>: <a href="https://linkedin.com/in/{{ resume.skype }}">{{ resume.skype }}</a><br>{% endif %}
              {% if resume.twitter %}<b>Twitter</b>: {{ resume.twitter }}<br>{% endif %}
              {% if resume.stackoverflow %}<b>stackoverflow</b>: <a href="http://stackoverflow.com/users/{{ resume.stackoverflow }}">{{ resume.stackoverflow }}</a><br>{% endif %}
              {% if resume.github %}<b>GitHub</b>: <a href="https://github.com/{{ resume.github }}">{{ resume.github }}</a><br>{% endif %}
          </td>
        </tr>
      </table>
      {% if trainings %}
        <hr class=separator>
        <h2 class="center h2">{% trans "Educations" %}</h2>
        {% for training in trainings %}
        <!--<h3 class="h3">{{ training.degree }} in <em style="color: #000">{{ training.school }}</em> <small>{% daterange_display training.year training.month %}</small></h3>-->
        <!--{% if not hide_training_description and training.description %}{{ training.description|linebreaksbr }}{% endif %}-->
         <h3 class="h3 ">
                     {% if training.field_of_study %}
                         {{ training.degree }} in {{training.field_of_study }}
                     {% else %}
                        {{ training.degree }}
                    {% endif %}
                     ( <small>{% daterange_display training.start_year training.start_month training.end_year training.end_month %}</small> )</h3>
                <p class="shiftword">{% if not hide_training_description and training.school %}{{ training.school|linebreaksbr }}{% endif %}</p>
                <p class="shiftword">{% if training.result %}Percentage: {{ training.result|linebreaksbr }}{% endif %}</p>
        {% endfor %}
      {% endif %}

      {% if skills %}
        <hr class=separator>
        <h2 class="center h2">{% trans "Skills" %}</h2>
        {% for skill in skills %}
        {% ifchanged skill.category %}
          <h3 class="h3">{{ skill.category|capfirst }}</h3>
        {% endifchanged %}
          {{ skill }},
        {% endfor %}
      {% endif %}

      {% if projects %}
        <hr class=separator>
        <h2 class="center h2">{% trans "Projects" %}</h2>
        {% for project in projects %}
          <h3 class="h3">{{ project.url|shortlink:project.title|safe }} <small> {% daterange_display project.start_year project.start_month project.end_year project.end_month %}</small></h3>
           <p>{{ project.description|linebreaksbr }}</p>
         <!--  <br>
          {{ project.still|linebreaksbr }}
          <br> -->
        {% endfor %}
      {% endif %}

      {% if experiences %}
        <hr class=separator>
        <h2 class="center h2">{% trans "Experiences" %}</h2>
        {% for experience in experiences %}
        <h3 class="h3">{{ experience }} <small>{% daterange_display experience.start_year experience.start_month experience.end_year experience.end_month %}</small></h3>
        {% if not hide_experience_description and experience.description %}{{ experience.description|linebreaksbr }}{% endif %}
        {% if not hide_experience_environment and experience.environment %}<br><br><b>{% trans "Technical environment" %}</b>: {{ experience.environment }}<br>{% endif %}
        {% endfor %}
      {% endif %}

      {% if certifications %}
        <hr class=separator>
        <h2 class="center h2">{% trans "Certifications" %}</h2>
        {% for certification in certifications %}
        <h3 class="h3">{{ certification.title }} <small>{% daterange_display certification.start_year certification.start_month %}</small></h3>
        {% if not hide_certification_description and certification.certification.description %}{{ certification.certification.description|linebreaksbr }}{% endif %}
        {% endfor %}
      {% endif %}

      {% if resume.hobbies %}
        <hr class=separator>
        <h2 class="center h2">{% trans "Hobbies" %}</h2>
        {{ resume.hobbies|linebreaksbr }}
      {% endif %}

      {% if resume.languages %}
      <hr class=separator>
      <h2 class="center h2">{% trans "Languages" %}</h2>
                  {% for language in resume.languages.all %}
                  {{ language }} - {{ language.get_level_display|capfirst|linebreaksbr }}
                  <br>
                  {% endfor %}
                {% endif %}
    </div>


 </body>
</html>

curriculum/templates/curriculum/experience.html
{% extends 'resume_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}
{% block content%}
<!-- <div class="headline">
	<h2>experience</h2></div> -->
<div class="col-lg-7 offset-3 mx-auto">

    <div class="col-md-12 col-lg-6">
                            <div class="row">

                                <div class="col-10">
                                    <a href="{%  url 'curriculum:updateexperience'   %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i> Update existing items
                                        </a>
                                </div>

                            </div>
                        </div>

    <div class="box border rounded">
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}

             <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.title|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.entreprise|as_crispy_field }}
      </div>
  </div>


  <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.description|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.type|as_crispy_field }}
      </div>
    </div>
   <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.start_year|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.start_month|as_crispy_field }}
      </div>
  </div>
  {{ form.still|as_crispy_field }}


  <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.end_year|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.end_month|as_crispy_field }}
      </div>
    </div>

            <input class="btn btn-info btn-lg btn-block" type="submit" value="save" />
        </form>
    </div>
</div>
   {% endblock %}

curriculum/templates/curriculum/menulist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
<!-- <style>
body {
  font-family: "Lato", sans-serif;
}


}
</style> -->
<!-- <link rel="stylesheet" href="{% static 'css/custom.css' %}"> -->

<div class="sidenav">
  <a href="/employee/resume">Resume</a><br>
        <a href="/employee/training">Education</a><br>
        <a href="/employee/skill">Skill</a><br>
        <a href="/employee/skillitem">Skill Item</a><br>
        <a href="/employee/project">Project</a><br>
        <a href="/employee/projectitem">Project Item</a><br>
        <a href="/employee/experience">Experience</a><br>
        <a href="/employee/certification">Certification</a><br>
        <a href="/employee/certificationitem">Certification Item</a><br>
        <a href="/employee/language">Language</a><br>
        <a href="/employee/languageitem">Language Item</a><br>
</div>
<div class="main">
        
</div>
{% endblock %}

curriculum/templates/curriculum/project.html
{% extends 'resume_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}
{% block content%}
<!-- <div class="headline">
    <div id="ani">
	<h1>project</h1></div>
</div> -->
<div class="col-lg-7 offset-3 mx-auto">
    <div class="box border rounded">
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %} 
            <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.title|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.url|as_crispy_field }}
      </div>
    </div>
            {{ form.description|as_crispy_field }}
            <input class="btn btn-info btn-lg btn-block" type="submit" value="save" />
        </form>
    </div>
</div>
   {% endblock %}

curriculum/templates/curriculum/resume_generate.html
{% extends 'base.html' %}

{% load static %}

{% block content%}
<div class="zoom">
	<div class="row">
		<div class="col-md-3 mb-0" id="colm">
			<a href="{% url 'curriculum:classic1' %}"><img class="image1" src="{% static 'img/template2.png' %}"></a>
		</div>

		<div class="col-md-3 mb-0">
  			<a href="{% url 'curriculum:modern' %}"> <img class="image1" src="{% static 'img/modern.JPG' %}"></a>
		</div>

		<div class="col-md-3 mb-0">
   			<a href="{% url 'curriculum:classic' %}"> <img class="image1" src="{% static 'img/classic.JPG' %}"></a>
		</div>

		<div class="col-md-3 mb-0">
   			<a href="{% url 'curriculum:test' %}"> <img class="image1" src="{% static 'img/classic_template.png' %}"></a>
		</div>
	</div>
</div>
	<!--<div style="text-align: right; font-size: 40px">-->
 <!--           <a href="{% url 'curriculum:viewCV' %}" class="badge badge-pill badge-primary">View Resume</a>-->
 <!--       </div>-->

	 <div class="sidebar-header">

    </div>
{% endblock %}

curriculum/templates/curriculum/skill.html
{% extends 'resume_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock %}
{% block content%}
<!-- <div class="headline">
	<h2>skill</h2></div> -->
<div class="col-lg-7 offset-3 mx-auto">
    <div class="box border rounded">
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %} 
            {{ form|crispy }}
            <input class="btn btn-info btn-lg btn-block" type="submit" value="save" />
        </form>
    </div>
</div>
   {% endblock %}