jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import activate
from django.contrib.auth import views as auth_views
from curriculum.views import export_single_page, export_classic, export_class,export_classic1,addlanguageitem,addresume, addskillitem, addcertificationitem, addexperience, addprojectitem, addtraining, menulist
from jobsapp.views import search_box

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/search/', search_box, name='search_box'),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),





    path('employee/', include('curriculum.urls')),





    path('activate/<uidb64>/<token>',
        activate, name='activate'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password/password_reset.html'
         ),
         name='password-reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password/password_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobsapp/urls.py
from django.urls import path, include

from .views import *
from jobsapp import views

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('candidate_search', CandidateSearchView.as_view(), name='candidate_search'),
    path('employer/create_profile', CompanyCreateView.as_view(), name='company_create_profile'),
    path('employer/update_profile', CompanyUpdateView.as_view(), name='company_update_profile'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('filterapplicants/<int:job_id>', FilterApplicantPerJobView.as_view(), name='filter-employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        path('applicant_profile/<int:id>', views.applicant_profile, name='applicant_profile'),
        path('download_profile/<int:id>', views.download_profile, name='download_profile'),
        # path('edit-jobpost/<int:id>', views.JobUpdateView.as_view(), name='employer-edit-jobpost'),

    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employee/appliedJobs', AppliedJobListView.as_view(), name ='appliedJobs' ),
    path('company_profile/<int:id>', views.company_profile, name='company_profile_from_jobDescription'),
    path('jobs-update/<int:id>', JobUpdateView.as_view(), name='jobs-update'),
    path('jobdelete/<int:id>', JobDeleteView.as_view(), name='jobs-delete'),
    #path('elasticsearch/',include('haystack.urls')),

    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    path('about', AboutUsView, name='aboutus'),

]

jobsapp/views/employer.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView,UpdateView

from jobsapp.decorators import user_is_employer, company_can_post
from jobsapp.forms import CreateJobForm, CreateCompanyForm, UpdateJobForm
from jobsapp.models import Job, Applicant , Company
from django.core.exceptions import PermissionDenied


from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.messages.views import SuccessMessageMixin

from fuzzywuzzy import process
from curriculum.models import Resume

class DashboardView(ListView):
    model = Job
    template_name = 'jobs/employer/dashboard.html'
    context_object_name = 'jobs'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class ApplicantPerJobView(ListView):
    model = Applicant
    template_name = 'jobs/employer/applicants.html'
    context_object_name = 'applicants'


    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.filter(job_id=self.kwargs['job_id']).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = Job.objects.get(id=self.kwargs['job_id'])
        return context

class FilterApplicantPerJobView(ListView):
    model = Applicant
    template_name = 'jobs/employer/applicants.html'
    context_object_name = 'applicants'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)



    def get_queryset(self):
        if self.request.GET['skill']:
            skillset= Resume.objects.all().values_list('skills__skill',flat=True)
            queryskill = self.request.GET['skill']
            tuple1= process.extractOne(queryskill, skillset,score_cutoff=80)
            if tuple1== None :
                queried_skill_match ='msdfnmasnfmnsfmn'
            else:
                queried_skill_match = tuple1[0]

        else:
            queried_skill_match=self.request.GET['skill']

        return Applicant.objects.filter(job_id=self.kwargs['job_id'],user__skills__skill__icontains=queried_skill_match).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = Job.objects.get(id=self.kwargs['job_id'])
        return context

# class JobCreateView(CreateView):
#     template_name = 'jobs/create.html'
#     form_class = CreateJobForm
#     extra_context = {
#         'title': 'Post New Job'
#     }
#     success_url = reverse_lazy('jobs:employer-dashboard')

#     @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
#     @method_decorator(user_is_employer)
#     @method_decorator(company_can_post)
#     def dispatch(self, request, *args, **kwargs):
#         if not self.request.user.is_authenticated:
#             return reverse_lazy('accounts:login')
#         if self.request.user.is_authenticated and self.request.user.role != 'employer':
#             return reverse_lazy('accounts:login')
#         return super().dispatch(self.request, *args, **kwargs)

#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         form.instance.company_name = Company.objects.values_list('company_name', flat=True ).get(user=self.request.user)
#         form.instance.company_description = Company.objects.values_list('company_description', flat=True ).get(user=self.request.user)
#         form.instance.website = Company.objects.values_list('website', flat=True ).get(user=self.request.user)
#         return super(JobCreateView, self).form_valid(form)

#     def post(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         form = self.get_form()
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)


#     def get_object(self , *args , **kwargs):
#         try:
#                 job = Job.objects.get(user=self.request.user)
#         except:
#                 job = None
#         return job


class JobCreateView(CreateView):
    template_name = 'jobs/create.html'
    form_class = CreateJobForm
    extra_context = {
        'title': 'Post New Job'
    }
    success_url = reverse_lazy('jobs:employer-dashboard')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    @method_decorator(company_can_post)
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'employer':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.company_name = Company.objects.values_list('company_name', flat=True ).get(user=self.request.user)
        form.instance.company_description = Company.objects.values_list('company_description', flat=True ).get(user=self.request.user)
        form.instance.website = Company.objects.values_list('website', flat=True ).get(user=self.request.user)
        return super(JobCreateView, self).form_valid(form)


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_object(self , *args , **kwargs):

        job = None
        return job

    # def get_queryset(self,request):
    #     return self.User.objects.filter(email=request.user)





class CompanyCreateView(CreateView):
    template_name = 'jobs/create_company.html'
    form_class = CreateCompanyForm
    extra_context = {
        'title': 'Create Company Profile'
    }
    success_url = reverse_lazy('jobs:home')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'employer':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.company_name = self.request.user.first_name
        form.instance.email = self.request.user.email
        form.instance.address = self.request.user.last_name
        return super(CompanyCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class CompanyUpdateView(UpdateView):
    model = Company
    fields = ['company_description','website','Phone']
    template_name = 'jobs/update_companyprofile.html'
    success_url = reverse_lazy('jobs:home')

    def get_object(self, queryset=None):
        obj = Company.objects.get(user=self.request.user)
        if obj is None:
            raise Http404("Company doesn't exists")
        return obj


class JobUpdateView(SuccessMessageMixin, UpdateView):
    model=Job
    template_name = 'jobs/update_job.html'
    form_class = UpdateJobForm
    context_object_name = 'job'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('jobs:employer-dashboard')
    # success_message = "Job is updated successfully"

    # def get_object(self, queryset=None):
    #     obj = super(JobUpdateView, self).get_object(queryset=queryset)
    #     if obj is None:
    #         raise Http404("Job doesn't exists")
    #     return obj

    def get_object(self, queryset=None):

        obj = super(JobUpdateView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")

        elif obj.user == self.request.user:
            return obj
        else:
            raise PermissionDenied




    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # redirect here
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_success_message(self, cleaned_data):
        #  cleaned_data is the cleaned data from the form which is used for string formatting
        return "Job is updated successfully"




class ApplicantsListView(ListView):
    model = Applicant
    template_name = 'jobs/employer/all-applicants.html'
    context_object_name = 'applicants'

    def get_queryset(self):
        # jobs = Job.objects.filter(user_id=self.request.user.id)
        return self.model.objects.filter(job__user_id=self.request.user.id).distinct()


@login_required(login_url=reverse_lazy('accounts:login'))
def filled(request, job_id=None):
    job = Job.objects.get(user_id=request.user.id, id=job_id)
    job.filled = True
    job.save()

templates/jobs/employer/all-applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">All applicants who applied for your position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4><a href="{% url 'jobs:applicant_profile' applicant.user.id %}">{{ applicant.user.get_full_name }}</a> <a href="{% url 'jobs:download_profile' applicant.user.id %}"><img src="{% static 'cv_download.png' %}" height="30" width="30" /></a></h4>
                            <p><strong>Applied position: {{ applicant.job.title }}</strong></p>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Contact
                            </a>
                            <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'user1.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <!-- <h3>You are end</h3> -->
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Applicants for the <span class="accent">{{ job.title }}</span> position</h1>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job-form-box">
                        <h4 class="heading">Filter <span class="accent">candidates</span> using
                            <span class="accent">skills</span>.
                        </h2>
                        <form id="job-main-form" method="get" action="{% url 'jobs:filter-employer-dashboard-applicants' job.id %}" class="job-main-form">

                            <div class="controls">
                                <div class="row align-items-center">

                                    <div class="col-md-7">
                                        <div class="form-group">
                                            <label for="location">Skills</label>
                                            <input type="text" id="skill" name="skill"
                                                   placeholder="Any particular skills?" class="form-control">
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <button type="submit"
                                                class="btn btn-outline-white-primary job-main-form__button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ applicants.count }}</span> candidates</h3>
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4><a href="{% url 'jobs:applicant_profile' applicant.user.id %}">{{ applicant.user.get_full_name }}</a> <a href="{% url 'jobs:download_profile' applicant.user.id %}"><img src="{% static 'cv_download.png' %}" height="30" width="30" /></a></h4>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Contact
                            </a>
                            <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'user1.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <!-- <h3>You are end</h3> -->
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">dashboard</h1>
                    <p class="lead text-center">All created jobs</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5"><a href="{% url 'jobs:employer-jobs-create' %}"
                                                          class="btn btn-outline-white-primary">
                   <img src="{% static 'add.png' %}" alt="" height="20" width="20"
                                         class="img-fluid rounded-circle"> Add new position</a></div>
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>Job title</th>
                                <th>Position filled</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                                <th>Applicants</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}

                                <tr>
                                    <th><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>
                                        {% if job.filled %}
                                            <span class="badge badge-success">Filled</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Not Filled</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ job.created_at }}</td>
                                    <td>{{ job.last_date }}</td>
                                    <td>
                                        <a href="{% url 'jobs:employer-dashboard-applicants' job.id %}"
                                           class="btn btn-success">
                                            <i class="fa fa-users"></i>{{ job.applicants.count }}
                                            <span class="hidden-xs hidden-sm">Applicants</span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'jobs:jobs-update' job.id  %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                        <br>
                                        {% if job.filled %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Filled</span>
                                            </a><br>
                                        {% else %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Mark as </span>filled
                                            </a><br>
                                        {% endif %}
                                        <a href="{% url 'jobs:jobs-delete' job.id %} " class="btn btn-outline-white-secondary">
                                            <i class="fa fa-times-circle-o"></i>Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}

                </div>
            </div>
        </div>
    </section>

{% endblock %}