accounts/urls.py
from django.urls import path, include



from django.conf import settings
from django.conf.urls.static import static

from jobsapp.views import EditProfileView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('employee/register/', RegisterEmployeeView.as_view(), name='employee-register'),
    path('employee/profile/', profile, name='employeeProfile'),
    path('employer/register/', RegisterEmployerView.as_view(), name='employer-register'),
    path('employee/profile/update/', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curriculum/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import *


app_name = "curriculum"

urlpatterns = [
    
    path('classic/',export_classic,name='classic'),
    path('classic1/',export_classic1,name='classic1'),
    path('modern/',export_single_page,name='modern'),
    #path('htmltest/<str:first_name>/',export_class,name='test'),
    path('viewCV/',export_class,name='viewCV'),
    path('profileview/',profileView,name='profileview'),
    path('htmltest/',export_classic2,name='test'),

    
    path('languageitem/',addlanguageitem,name='languageitem'),
    path('resume/',addresume,name='resume'),
    # path('skill/',addskill,name='skill'),
    path('skillitem/',addskillitem,name='skillitem'),
    # path('certification/',addcertification,name='certification'),
    path('certificationitem/',addcertificationitem,name='certificationitem'),
    path('experience/',addexperience,name='experience'),
    # path('project/',addproject,name='project'),
    path('projectitem/',addprojectitem,name='projectitem'),
    path('training/',addtraining,name='training'),
    path('cv/',resume_generate,name='resume_generate'),
    path('edit_profile/',menulist,name='showmenu'),
    path('updateresume/',EditProfileView.as_view(),name='updateResume'),
    

    path('updatetraining/',TrainingListView.as_view(),name='updatetraining'),
    path('updatetraining/<int:id>', UpdateTrainingView.as_view(), name='update_training'),
    path('deletetraining/<int:id>', TrainingDeleteView.as_view(), name='delete_training'),

    path('updateskill',SkillListView.as_view(),name='updateskill'),
    path('updateskill/<int:id>', UpdateSkillView.as_view(), name='update_skill'),
    path('deleteskill/<int:id>', SkillDeleteView.as_view(), name='delete_skill'),


    path('updateproject',ProjectListView.as_view(),name='updateproject'),
    path('updateproject/<int:id>', UpdateProjectView.as_view(), name='update_project'),
    path('deleteproject/<int:id>', ProjectDeleteView.as_view(), name='delete_project'),





    path('updatelanguage',LanguageListView.as_view(),name='updatelanguage'),
    path('updatelanguage/<int:id>', UpdateLanguageView.as_view(), name='update_language'),
    path('deletelanguage/<int:id>', LanguageDeleteView.as_view(), name='delete_language'),


    path('updateexperience',ExperienceListView.as_view(),name='updateexperience'),
    path('updateexperience/<int:id>', UpdateExperienceView.as_view(), name='update_experience'),
    path('deleteexperience/<int:id>', ExperienceDeleteView.as_view(), name='delete_experience'),


    path('updatecertification',CertificationListView.as_view(),name='updatecertification'),
    path('updatecertification/<int:id>', UpdateCertificationView.as_view(), name='update_certification'),
    path('deletecertification/<int:id>', CertificationDeleteView.as_view(), name='delete_certification'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import activate
from django.contrib.auth import views as auth_views
from curriculum.views import export_single_page, export_classic, export_class,export_classic1,addlanguageitem,addresume, addskillitem, addcertificationitem, addexperience, addprojectitem, addtraining, menulist
from jobsapp.views import search_box

from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/search/', search_box, name='search_box'),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),





    path('employee/', include('curriculum.urls')),





    path('activate/<uidb64>/<token>',
        activate, name='activate'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password/password_reset.html'
         ),
         name='password-reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password/password_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobsapp/urls.py
from django.urls import path, include

from .views import *
from jobsapp import views

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('candidate_search', CandidateSearchView.as_view(), name='candidate_search'),
    path('employer/create_profile', CompanyCreateView.as_view(), name='company_create_profile'),
    path('employer/update_profile', CompanyUpdateView.as_view(), name='company_update_profile'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('filterapplicants/<int:job_id>', FilterApplicantPerJobView.as_view(), name='filter-employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
        path('applicant_profile/<int:id>', views.applicant_profile, name='applicant_profile'),
        path('download_profile/<int:id>', views.download_profile, name='download_profile'),
        # path('edit-jobpost/<int:id>', views.JobUpdateView.as_view(), name='employer-edit-jobpost'),

    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employee/appliedJobs', AppliedJobListView.as_view(), name ='appliedJobs' ),
    path('company_profile/<int:id>', views.company_profile, name='company_profile_from_jobDescription'),
    path('jobs-update/<int:id>', JobUpdateView.as_view(), name='jobs-update'),
    path('jobdelete/<int:id>', JobDeleteView.as_view(), name='jobs-delete'),
    #path('elasticsearch/',include('haystack.urls')),

    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    path('about', AboutUsView, name='aboutus'),

]

jobsapp/views/home.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.db.models import F,Value, CharField, Q
from django.db.models.functions import Concat

from django.core.exceptions import ObjectDoesNotExist

from jobsapp.forms import ApplyJobForm
from jobsapp.models import Job, Applicant, Company
from accounts.models import User
from curriculum.models import Resume,ProjectItem,SkillItem,CertificationItem,Training,Experience,LanguageItem
from django.shortcuts import get_object_or_404
from curriculum.models import *
from fuzzywuzzy import process

from curriculum import export
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied



from jobsapp.decorators import user_can_search,user_is_employer,user_is_superuser

class HomeView(ListView):
    model = Job
    template_name = 'home.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(last_date__gte=timezone.now())[:6]
        #return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated and self.request.user.role == 'employee' and self.request.user.skills.exists() :
            current_user= Resume.objects.get(user=self.request.user)
            skillset= SkillItem.objects.filter(resume=current_user).values_list('skill',flat=True)
            for skill in skillset:
                if self.model.objects.filter(skills__icontains=skill).exists():
                    context['recommendations'] = self.model.objects.filter(skills__icontains=skill,last_date__gte=timezone.now()).distinct()[:3]

        else:
            context['trendings'] = self.model.objects.filter(last_date__gte=timezone.now())[:3]
            #context['trendings'] = self.model.objects.all()[:3]
        return context


class SearchView(ListView):
    model = Job
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    # def get_queryset(self):
    #     return self.model.objects.filter(location__icontains=self.request.GET['location'],
    #                                      title__icontains=self.request.GET['position'],
    #                                      type__icontains=self.request.GET['type']).distinct()

    def get_queryset(self):

        if self.request.GET['location']:
            locationset= Job.objects.all().values_list('location',flat=True)
            querylocation = self.request.GET['location']
            tuple1= process.extractOne(querylocation, locationset)
            queried_location_match = tuple1[0]
        else:
            queried_location_match = self.request.GET['location']


        if self.request.GET['position']:
            titleset = Job.objects.all().values_list('title',flat=True)
            querytitle = self.request.GET['position']
            tuple2= process.extractOne(querytitle, titleset)
            queried_title_match = tuple2[0]
        else:
            queried_title_match = self.request.GET['position']


        return self.model.objects.filter(location__icontains=queried_location_match,
                                         title__icontains=queried_title_match,
                                         type__icontains=self.request.GET['type'],last_date__gte=timezone.now()).distinct()



class CandidateSearchView(ListView):
    model = Resume
    template_name = 'jobs/candidate_search.html'
    context_object_name = 'candidates'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_can_search)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):

        if self.request.GET['skill']:
            skillset= Resume.objects.all().values_list('skills__skill',flat=True)
            queryskill = self.request.GET['skill']
            tuple1= process.extractOne(queryskill, skillset,score_cutoff=70)
            if tuple1== None :
                queried_skill_match ='msdfnmasnfmnsfmn'
            else:
                queried_skill_match = tuple1[0]

        else:
            queried_skill_match=self.request.GET['skill']


        if self.request.GET['position']:
            experienceset = Resume.objects.all().values_list('experiences__title',flat=True)
            queryexperience = self.request.GET['position']
            tuple2= process.extractOne(queryexperience, experienceset,score_cutoff=70)
            if tuple2 == None :
                queried_experience_match ='mfnmandfmndmfnnmd'
            else:
                queried_experience_match = tuple2[0]

        else:
            queried_experience_match=self.request.GET['position']




        resume_modified = self.model.objects.all().annotate(YOE=F('experiences__end_year')-F('experiences__start_year'),QUAL=Concat('trainings__degree', Value(' in '), 'trainings__field_of_study'))

        # educationset = resume_modified.values_list('QUAL',flat=True)
        # queryeducation = self.request.GET['qualification']
        # tuple3= process.extractOne(queryeducation, educationset)
        # queried_qualification_match = tuple3[0]


        # returned_users=resume_modified.values('user').filter(experiences__title__icontains=self.request.GET['position'],
        #                               skills__skill__icontains=self.request.GET['skill'],
        #                               YOE__gte=self.request.GET['experience'],
        #                               QUAL__icontains=self.request.GET['qualification']).distinct().order_by('-skills_level','-YOE')

        returned_users=resume_modified.values('user').filter(experiences__title__icontains=queried_experience_match,
                                      skills__skill__icontains=queried_skill_match,
                                      YOE__gte=self.request.GET['experience'],
                                       QUAL__icontains=self.request.GET['qualification']).distinct().order_by('-skills_level','-YOE')



        return self.model.objects.filter(user__in=returned_users)



class JobListView(ListView):
    model = Job
    template_name = 'jobs/jobs.html'
    context_object_name = 'jobs'
    paginate_by = 5

def applicant_profile(request,id):
    user = User.objects.get(id=id)
    resume = get_object_or_404(Resume.objects.filter(user=user))
    context = {
        'pagesize': 'a4',
        'resume': resume,
        'skills': user.skills.order_by('category'),
        'projects': user.projects.order_by('-weight'),
        'experiences': user.experiences.order_by('-start_year'),
        'trainings': user.trainings.order_by('-start_year', '-start_month'),
        'certifications': user.certifications.order_by('-end_year', '-end_month'),
    }
   # return get_template('curriculum/test1.html').render(context)
    return render(request,'curriculum/cvpreview.html',context)


def company_profile(request,id):
    user= User.objects.get(id=id)
    company= get_object_or_404(Company.objects.filter(user=user))
    current_user = request.user
    context = {

        'company': company,

    }
    return render(request,'jobs/company_profile.html',context)




def download_profile(request,id):
    """Get a resume in a PDF with classic format."""
    #resume = get_object_or_404(Resume.objects.filter(id=resume_id))
    #resume = get_object_or_404(Resume.objects.filter(user=request.user))
    user = User.objects.get(id=id)
    current_user=user
    pdf, result = export.export_pdf(current_user, export.classic2)
    raw_pdf = result.getvalue()
    if not pdf.err:
        return HttpResponse(raw_pdf, content_type='application/pdf')
    return HttpResponse('We had some errors.')



class JobDetailsView(DetailView):
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # redirect here
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    # def get_context_data(self, **kwargs):
    #   context = super().get_context_data(**kwargs)
    #   job = self.get_object()
    #   context['company'] = Company.objects.filter(user=job.user)
    #   return context


class ApplyJobView(CreateView):
    model = Applicant
    form_class = ApplyJobForm
    slug_field = 'job_id'
    slug_url_kwarg = 'job_id'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     form = self.get_form()
    #     if form.is_valid():
    #         messages.info(self.request, 'Successfully applied for the job!')
    #         return self.form_valid(form)
    #     else:
    #         return HttpResponseRedirect(reverse_lazy('jobs:home'))

    def post(self, request, *args, **kwargs):
        try  :
            resume = self.request.user.resumes
            form = self.get_form()
            if form.is_valid():
                messages.info(self.request, 'Successfully applied for the job!')
                return self.form_valid(form)
            else:

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    About Us
{% endblock %}

{% block content %}

<body style ="background-color: #D8BFD8;">
  <div class="row about">
    <div class="col-lg-12" style="text-align: center;">
    <a target="_self" href="#" class="imgButton one">
        <img class="rounded-circle mx-auto d-block" src="{% static 'img/profile.jpg'%}" width="200" height="200" ></a>
      <p> Name: Suman Khatri<br>
      id: </p>
    <div class="col-lg-12">
  </div>

  <div class="row about">
    <div class="col-lg-3">
      <a target="_self" href="#" class="imgButton one">
        <img class="rounded-circle mx-auto d-block" src="{% static 'img/profile.jpg'%}" width="200" height="200" ></a>
      <p> Name: Suman Khatri<br>
      id: </p>
    </div>
    <div class="col-lg-3">
      <a target="_self" href="#" class="imgButton two">
        <img class="rounded-circle mx-auto d-block" src="{% static 'img/profile.jpg'%}" width="200" height="200" ></a>
      <p>suman khatri</p>
    </div>
    <div class="col-lg-3">
      <a target="_self" href="#" class="imgButton three">
        <img class="rounded-circle mx-auto d-block" src="{% static 'img/profile.jpg'%}" width="200" height="200" ></a>
      <p>suman khatri</p>
    </div>
    <div class="col-lg-3">
      <a target="_self" href="#" class="imgButton four">
        <img class="rounded-circle mx-auto d-block" src="{% static 'img/profile.jpg'%}" width="200" height="200" ></a>
      <p>Suman khatri</p>
    </div>
  </div>
</body>


{% endblock %}

templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.first_name }},

Thank you for joing us. You are just one click away from getting connected to us.
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}


Please try resetting your password if the activation link shows "Activation link inavlid!!" error. In case of any other issues, please report to the department.

Department of Electronics and Computer Engineering
Institute of Engineering, Pulchowk Campus
Pulchowk, Lalitpur


+977-1-5534070
ece@ioe.edu.np
P.O. Box No. 1915, Pulchowk, Lalitpur
{% endautoescape %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>  {% block title %} {% endblock %} - Pulchowk Job Portal</title>
    <link rel="icon" type="image/gif/png" href="{% static 'img/TU_logo.png' %}">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
          href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
          href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
          id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block styles %}{% endblock %}
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">

<body>

<!-- navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg" style="background-color:#DCDCDC">
        <div class="container">
            <a href="/" class="navbar-brand">
                <img src="{% static 'img/logo.png' %}" width ="50" height="50" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>
            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <a href="/" class="nav-link active">Home <span class="sr-only">(current)</span></a>
                    </li>
                    {% if request.user.is_authenticated and request.user.role == 'employer' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle  mb-3 mb-lg-0 mt-3 mt-lg-0">

                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'jobs:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
                                <a href="{% url 'jobs:company_update_profile' %}" class="dropdown-item">Update Company Info</a>
                                <a href="{% url 'jobs:employer-all-applicants' %}" class="dropdown-item">Applicants </a>
                                <a href="{% url 'jobs:employer-jobs-create' %}" class="dropdown-item">Post a new
                                    job </a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% elif request.user.is_authenticated and request.user.role == 'employee' %}
                    <li class="nav-item">
                        <a href="{% url 'curriculum:resume_generate' %}" class="nav-link">CV Templates</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'curriculum:profileview' %}" class="nav-link">View Profile</a>
                    </li>

                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle mb-3 mb-lg-0 mt-3 mt-lg-0">

                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">

                                <a href="{% url 'curriculum:resume' %}" class="dropdown-item">Create CV</a>
                                <a href="{% url 'curriculum:updateResume' %}" class="dropdown-item">Update CV</a>
                                <a href="{% url 'jobs:appliedJobs' %}" class="dropdown-item">Applied jobs</a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% else %}
                     <li class="nav-item ">

                    <a href="/admin" class="navbar-brand">
                <i class="fa fa-user"></i>
                Admin
            </a>
            </li>

                        <li class="nav-item dropdown">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle">

                               Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a href="{% url 'accounts:employee-register' %}" class="dropdown-item">Student</a>
                                <a href="{% url 'accounts:employer-register' %}" class="dropdown-item">Company</a>
                            </div>
                        </li>
                        <li class="nav-item ">
                        <a></a>
                    </li>
                        <li class="nav-item" style="color: #fff; margin-top:12px">
                            <a href="{% url 'accounts:login' %}">
                                <button class="btn btn-my">Login</button>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<div>
    <div style="margin-left: 250px; margin-right: 250px">
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
{#            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>#}
        {% endfor %}

    {% endif %}

</div>



{% block resume %}{% endblock %}

    {% block content %} {% endblock %}


{% block footer%}
<footer class="footer">
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-md-left text-center">
                    <p>&copy;2019 Job Portal for Pulchowk Campus</p>
                </div>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>

{% block javascripts %}{% endblock %}

</body>

</html>

templates/update_base.html
{% extends 'base.html' %}
{% block resume %}


<style>

    /* The side navigation menu */
.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

/* Sidebar links */
.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}

/* Active/current link */
.sidebar a.active {
  background-color: #4CAF50;
  color: white;
}

/* Links on mouse-over */
.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

/* Page content. The value of the margin-left property should match the value of the sidebar's width property */
div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
}

/* On screens that are less than 700px wide, make the sidebar into a topbar */
@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

/* On screens that are less than 400px, display the bar vertically, instead of horizontally */
@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
</style>

<!--<div class="sidenav">-->
    <div class="sidebar">
    <div class="sidebar-header">
            <h3>My Resume</h3>
            <!--<a href=""><img class="rounded-circle" style=" margin-left: 20px"width ="70" height="70" src="{{ user.profile.image.url }}"></a>-->
    </div>
    <br>
        <a href="{% url 'curriculum:updateResume' %}" class="{{ resume_active }}"><i class="fa fa-address-book" style="font-size:18px;color:#2F4F4F"></i>Basic Info</a>
        <a href="{% url 'curriculum:updatetraining' %}" class="{{ training_active }}"><i class='fa fa-graduation-cap' style='font-size:18px;color:#2F4F4F'></i>Education</a>
        <a href="{% url 'curriculum:updateproject' %}" class="{{ project_active }}"><i class="fa fa-address-book" style="font-size:18px;color:#2F4F4F"></i>Project</a>
        <a href="{% url 'curriculum:updateskill' %}" class="{{ skill_active }}"><i class='fa fa-graduation-cap' style='font-size:18px;color:#2F4F4F'></i>Skill</a>
        <a href="{% url 'curriculum:updateexperience' %}" class="{{ experience_active }}"><i class="fa fa-address-book" style="font-size:18px;color:#2F4F4F"></i>Experience</a>
        <a href="{% url 'curriculum:updatecertification' %}" class="{{ certification_active }}"><i class='fa fa-graduation-cap' style='font-size:18px;color:#2F4F4F'></i>Certification</a>
        <a href="{% url 'curriculum:updatelanguage' %}" class="{{ language_active }}"><i class="fa fa-address-book" style="font-size:18px;color:#2F4F4F"></i>Language</a>


</div>
{% endblock %}
{% block footer %}
{% endblock %}